<!DOCTYPE html>
<html lang="ua-UA">
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108483747-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108483747-1');
</script>
<meta charset="utf-8">
<title>Деталі трубопроводів стальні зварні</title>
<link rel="shortcut icon" href="http://euromash.kiev.ua/images/favicon.png"  type="image/x-icon">
<meta name="description" content="ДДеталі трубопроводів стальні зварні" />
<meta name="keywords" content="Деталі трубопроводів стальні зварні, обладнання для нафтогазопроводів, Україна, Фастів" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<link rel="stylesheet" href="../style/nstyle.css" type="text/css" media="screen" />
<link rel="stylesheet" href="../contact_menu/contact-blue.css" type="text/css" media="screen">
<link rel="stylesheet" type="text/css" media="screen" href="../style/font-awesome.css" />
<link rel="stylesheet" type="text/css" media="screen" href="../style/mobile.css" />
<script type="text/javascript" src="../jquery/jquery-1.5.2.js"></script>
<style type="text/css">
TABLE {
    width: 99%; /* Ширина таблицы */
	margin: auto;
    border-collapse: collapse; /* Убираем двойные линии между ячейками */
	font-size: 150%;
   }
   TD, TH {
    text-align: center;
	padding: 1px; /* Поля вокруг содержимого таблицы */
    border: 1px solid black; /* Параметры рамки */
   }
   TH {
	text-align: center;   
    background: #28528C; /* Цвет фона */
   }
</style>
<body>
<div id="container">
<?php
$punkt='catalog_ua';
include "menu_ua.php";
?>

<?php
include "header_img.php";
?>
<div id="breadcrumbs">
	<ul>
		<li><a href="home_ua.php">Про компанію</a></li>
		<li><a href="catalog_ua.php">Продукція</a></li>
		<li><a href="oborudovanie_neftegazoprovodov_ua.php">Обладнання для нафтогазопроводів</a></li>
		<li><a href="#">Деталі трубопроводів стальні зварні</a></li>
	</ul>
</div>
<div id="lang">
  <div id="button_ua">
  <a class="but_ua" href="http://euromash.kiev.ua/ua/detali_truboprovodov_ua.php" title="Українська версія сторінки"></a>
     <div id="button_uk">
     <a class="but_uk" href="http://euromash.kiev.ua/en/detali_truboprovodov_en.php" title="English version of the page"></a>
  <div id="button_ru">
  <a class="but_ru" href="http://euromash.kiev.ua/ru/detali_truboprovodov_ru.php" title="Русская версия страницы"></a>
  </div>
     </div>
  </div>
</div>
<div id="main">
<h1><strong>Деталі трубопроводів стальні зварні</strong></h1>
<p>Деталі трубопроводів призначені для лінійних трубопроводів та технологічних обв'язок насосних та компресорних станцій, а також трубопроводів на які розповсюджуються Правила Держнаглядохоронпраці. Деталі трубопроводів виготовляються діаметром від 57 мм до 1420 мм на робочий тиск до 16 МПа (160 кгс/см<sup>2</sup>).</p>
<p>ТОВ "ГК ЄВРОХІММАШ К.О." виготовляє наступний асортимент деталей трубопроводів:</p>
<p>1. Відводи трубопроводів зварні:<br>
a) Відводи секційні з радіусом повороту 1,5Ду</p>
<img class="center" id="img-w-500" src="http://euromash.kiev.ua/images/prod/truboprovod/detal/otvod1-5.jpg" alt="">
<p>Таблиця 1 - Відводи секційні з радіусом повороту 1,5Ду</p>
<table>
        <tr>
			<th rowspan="2">Діаметр зовнішній, Д<sub>з</sub></th>
			<th rowspan="2">Радіус вигину, R</th>
			<th colspan="4">Будівельна довжина L, для кутів повороту</th>
        </tr>
        <tr>
            <th>90&deg;</th>
			<th>60&deg;</th>
            <th>45&deg;</th>
            <th>30&deg;</th>
        </tr>
		<tr>
            <td>530</td>
			<td>750</td>
            <td>750</td>
            <td>433</td>
			<td>311</td>
            <td>201</td>
        </tr>
		<tr>
            <td>630</td>
			<td>900</td>
            <td>900</td>
            <td>520</td>
			<td>373</td>
            <td>241</td>
        </tr>
		<tr>
            <td>720</td>
			<td>1000</td>
            <td>1000</td>
            <td>577</td>
			<td>414</td>
            <td>268</td>
        </tr>
		<tr>
            <td>820</td>
			<td>1200</td>
            <td>1200</td>
            <td>693</td>
			<td>497</td>
            <td>321</td>
        </tr>
		<tr>
            <td>1020</td>
			<td>1500</td>
            <td>1500</td>
            <td>866</td>
			<td>621</td>
            <td>402</td>
        </tr>
		<tr>
            <td>1220</td>
			<td>1800</td>
            <td>1800</td>
            <td>1039</td>
			<td>746</td>
            <td>482</td>
        </tr>
		<tr>
            <td>1420</td>
			<td>2100</td>
            <td>2100</td>
            <td>1212</td>
			<td>870</td>
            <td>562</td>
        </tr>
    </table>
<p>&nbsp;<br>
б) Відводи секційні з радіусом повороту 5Ду</p>
<div class="img_2_center">
<img id="img-w-500" src="http://euromash.kiev.ua/images/prod/truboprovod/detal/otvod_30_5.jpg" alt="">
<img id="img-w-500" src="http://euromash.kiev.ua/images/prod/truboprovod/detal/otvod_45_5.jpg" alt="">
<img id="img-w-500" src="http://euromash.kiev.ua/images/prod/truboprovod/detal/otvod_90_5.jpg" alt="">
</div>
<p>Таблиця 2 - Відводи секційні з радіусом повороту 5Ду</p>
<table class="hide-240-399">
        <tr>
			<th rowspan="2">Діаметр зовнішній, Д<sub>з</sub></th>
			<th rowspan="2">Радіус вигину, R</th>
			<th colspan="9">Будівельна довжина L, для кутів повороту</th>
        </tr>
        <tr>
            <th>3&deg;</th>
			<th>6&deg;</th>
            <th>9&deg;</th>
            <th>12&deg;</th>
			<th>15&deg;</th>
			<th>30&deg;</th>
            <th>45&deg;</th>
            <th>60&deg;</th>
			<th>90&deg;</th>
        </tr>
		<tr>
            <td>530</td>
			<td>2500</td>
            <td>65</td>
            <td>131</td>
			<td>197</td>
            <td>263</td>
			<td>329</td>
            <td>670</td>
            <td>1036</td>
			<td>1443</td>
            <td>1036</td>
        </tr>
		<tr>
            <td>630</td>
			<td>3000</td>
            <td>79</td>
            <td>157</td>
			<td>236</td>
            <td>315</td>
			<td>395</td>
            <td>804</td>
            <td>1243</td>
			<td>1732</td>
            <td>1243</td>
        </tr>
		<tr>
            <td>720</td>
			<td>3500</td>
            <td>92</td>
            <td>183</td>
			<td>275</td>
            <td>368</td>
			<td>461</td>
            <td>938</td>
            <td>1450</td>
			<td>2020</td>
            <td>1450</td>
        </tr>
		<tr>
            <td>820</td>
			<td>4000</td>
            <td>105</td>
            <td>210</td>
			<td>315</td>
            <td>420</td>
			<td>527</td>
            <td>1072</td>
            <td>1657</td>
			<td>2309</td>
            <td>1657</td>
        </tr>
		<tr>
            <td>1020</td>
			<td>5000</td>
			<td>131</td>
			<td>262</td>
			<td>394</td>
			<td>526</td>
			<td>658</td>
			<td>1340</td>
			<td>2071</td>
			<td>2887</td>
			<td>2071</td>
        </tr>
		<tr>
            <td>1220</td>
			<td>6000</td>
			<td>157</td>
			<td>314</td>
			<td>472</td>
			<td>631</td>
			<td>790</td>
			<td>1608</td>
			<td>2485</td>
			<td>3464</td>
			<td>2485</td>
        </tr>
		<tr>
            <td>1420</td>
			<td>7000</td>
			<td>183</td>
			<td>367</td>
			<td>551</td>
			<td>736</td>
			<td>922</td>
			<td>1876</td>
			<td>2899</td>
			<td>4041</td>
			<td>2899</td>
        </tr>
    </table>
<p>2. Трійники зварні з накладками:</p>
<img class="center" id="img-w-500" src="http://euromash.kiev.ua/images/prod/truboprovod/detal/troynik.jpg" alt="">
<p>Таблиця 3 - Трійники зварні з накладками</p>
<table class="hide-240-399">
        <tr>
			<th rowspan="2">Зовнішній діаметр<br>магістралі, Д<sub>з</sub></th>
			<th colspan="12">Зовнішній діаметр відгалудження, d<sub>з</sub></th>
			<th colspan="2">Розміри, мм</th>
        </tr>
        <tr>
            <th>219</th>
			<th>273</th>
            <th>325</th>
            <th>377</th>
			<th>426</th>
			<th>530</th>
			<th>630</th>
            <th>720</th>
            <th>820</th>
			<th>1020</th>
			<th>1220</th>
			<th>1240</th>
			<th>L</th>
			<th>H</th>
        </tr>
		<tr>
			<td rowspan="6">530</td>
			<td>X</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>300</td>
			<td>450</td>
        </tr>
		<tr>
			<td>-</td>
            <td>X</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>350</td>
			<td>450</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>450</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>450</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>490</td>
			<td>450</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>450</td>
        </tr>
		<tr>
			<td rowspan="7">630</td>
			<td>X</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>300</td>
			<td>490</td>
        </tr>
		<tr>
			<td>-</td>
            <td>X</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>350</td>
			<td>500</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>500</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>500</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>490</td>
			<td>500</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>500</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>670</td>
			<td>530</td>
        </tr>
		<tr>
			<td rowspan="6">720</td>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>560</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>560</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>500</td>
			<td>560</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>560</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>670</td>
			<td>560</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>750</td>
			<td>580</td>
        </tr>
		<tr>
			<td rowspan="7">820</td>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>630</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>630</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>490</td>
			<td>630</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>630</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>670</td>
			<td>630</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>750</td>
			<td>630</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>850</td>
			<td>670</td>
        </tr>
		<tr>
			<td rowspan="8">1020</td>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>490</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>670</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>750</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>850</td>
			<td>750</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>1030</td>
			<td>850</td>
        </tr>
		<tr>
			<td rowspan="9">1220</td>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>850</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>850</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>490</td>
			<td>850</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>900</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>670</td>
			<td>900</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>750</td>
			<td>900</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>850</td>
			<td>900</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>1030</td>
			<td>950</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>1220</td>
			<td>1000</td>
        </tr>
		<tr>
			<td rowspan="10">1420</td>
			<td>-</td>
            <td>-</td>
            <td>X</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>400</td>
			<td>950</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>X</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>440</td>
			<td>950</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>490</td>
			<td>950</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>580</td>
			<td>1000</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>670</td>
			<td>1000</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>750</td>
			<td>1000</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>850</td>
			<td>1030</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>-</td>
			<td>1030</td>
			<td>1030</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>-</td>
			<td>1220</td>
			<td>1090</td>
        </tr>
		<tr>
			<td>-</td>
            <td>-</td>
            <td>-</td>
			<td>-</td>
            <td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>-</td>
			<td>X</td>
			<td>1400</td>
			<td>1150</td>
        </tr>
</table>
<p>3. Днища еліптичні штамповані<br>
Згідно ГОСТ 6533-78 днища еліптичні штамповані виготовляються по розміру зовнішнього діаметра 159, 219, 273, 325, 377, 426 мм.</p>
<p>По розміру внутрішнього діаметра днища виготовляються 400, 450, 480, 500, 600, 650, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1550, 1600, 1700, 1800, 1900, 2000 мм.</p>
<img class="center" id="img-w-500" src="http://euromash.kiev.ua/images/prod/truboprovod/detal/dnishche.jpg" alt="">
<p>4. Різні види фланців та фланцевих з'єднань.</p>
<p>&emsp;</p>

</div>
<?php
include "r_bar_ua.php";
?>
</div>
<?php
include "call_ua.php";
?>
</body>
</html>